### ISSUE TITLE
"Can't read configuration: default.conf" when no config is provided

### ISSUE THREAD

**Issue by fwilhe2** [uhafner/autograding-github-action#237]
Hi,

I was looking for a github actions counterpart to the Warnings NG plugin, and this action seems to be pretty close (even when I understand it was made for a different purpose), so I tried it out and I had this strange error when using it without explicit configuration:

```
No configuration provided (environment CONFIG not set), using default configuration
Can't read configuration: default.conf
```

This is the workflow run: https://github.com/fwilhe2/spring-petclinic/actions/runs/4983874769/jobs/8921470121

Here is that version of the workflow causing the error: https://github.com/fwilhe2/spring-petclinic/blob/d9f25097ea4a670d2f33dc9d31830ffca6256cba/.github/workflows/maven-build.yml

This can be mitigated by providing a custom config, but still the default config should be picked up. I have not investigated the issue, I'm assuming it's an issue with the file path in the docker image?

(Sidenote: To me it was not obvious from the readme that the config should be provided inline, making this a bit more clear in the readme would be great, I would gladly provide a PR for that.)

**Comment by uhafner** [comment]
Thanks for reporting. Since I always use a predefined configuration as part of my workflows I never noticed that I broke this part. 

It would be really helpful if you can provide a PR that makes it more clear on how to use it. I started the project during the Corona lockdown to help students to get faster feedback on their assignments but did not spent much time after that... 

My plan is to split this action into two parts so one can use it separately to report issues and code coverage (aka warnings and coverage Jenkins plugins) and on top of that the auto grading for students.

**Comment by uhafner** [comment]
I published a new action now: https://github.com/uhafner/quality-monitor

This additional action only shows all issues and the code coverage (without the grading step).
